recipe: default.v1
# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
# rasa train --fixed-model-name iwillfindyou_bot
language: ko

pipeline:
  - name: "custom.mecab_tokenizer.mecabtok_3.MecabTokenizer"
    "intent_tokenization_flag": False
    # Symbol on which intent should be split
    "intent_split_symbol": "_"
    # Regular expression to detect tokens
    "token_pattern": None
  - name: "custom.gloVe_featurizer.gloVe_feature.GloveFeaturizer"
    alias: "gloVe"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 50
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 50
  - name: RulePolicy